
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: 1024563964
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: airbnb_development

test:
  <<: *default
  database: airbnb_test

production:
  <<: *default
  database: airbnb_production
  username: airbnb
  password: <%= ENV["AIRBNB_DATABASE_PASSWORD"] %>

